databases:
  - name: scoreboard
    plan: free
    databaseName: scoreboard3
    database:user: scoreboard_2vf9_user
    user: scoreboard_2vf9_user
    

services:
  - type: web
    plan: free
    name: scoreboard
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn scoreboard.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scoreboard3
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 









