# Generated by Django 5.1 on 2024-08-10 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='games',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='library',
            name='games',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='games',
        ),
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='library', to='scoreboard.user'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='scoreboard.user'),
        ),
        migrations.AddField(
            model_name='library',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='library', to='scoreboard.game'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='scoreboard.game'),
        ),
        migrations.DeleteModel(
            name='Developers',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
