# Generated by Django 5.1 on 2024-08-10 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='game',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='game',
        ),
        migrations.CreateModel(
            name='LibraryCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='librarycatalogue', to='scoreboard.game')),
                ('library', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='librarycatalogue', to='scoreboard.library')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlistcatalogue', to='scoreboard.game')),
                ('wishlist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlistcatalogue', to='scoreboard.wishlist')),
            ],
        ),
    ]
