# Generated by Django 5.1 on 2024-08-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_game_remove_games_developers_remove_library_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='photo_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
