# Generated by Django 5.1 on 2024-08-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_game_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=1048576),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_url',
            field=models.CharField(max_length=1048576, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=1048576),
        ),
    ]
