# Generated by Django 5.1 on 2024-08-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_alter_game_description_alter_game_photo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Catalogue', to='scoreboard.game')),
            ],
        ),
    ]
